spring:
  application:
    name: AnmoryBlog
  datasource:
    url: jdbc:mysql://175.24.205.213:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: username
    password: lmjnb666
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: sk-fuacnJoLzVOp55Mq5PIFnpuYYemqwLDNdiyO8zW0j2fFZprd
      base-url: https://api.xty.app
      image:
        api-key: sk-fuacnJoLzVOp55Mq5PIFnpuYYemqwLDNdiyO8zW0j2fFZprd
        base-url: https://api.xty.app
      audio:
        speech:
          api-key: sk-fuacnJoLzVOp55Mq5PIFnpuYYemqwLDNdiyO8zW0j2fFZprd
          base-url: https://api.xty.app
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8087
  servlet:
    session:
      timeout: PT876000H